# -*- coding: utf-8 -*-
"""lab 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s0KR7VU4V3OLWxt7wBlPYcDKzCrTmkMs
"""

!unzip "lab2_aiot_public_dataset_deploy 2.zip"

# Commented out IPython magic to ensure Python compatibility.
# %cd "lab2_aiot_public_dataset_deploy 2"

!ls

!pip install -r requirements.txt

!python src/run_training_pipeline.py

!python src/check_outputs.py

import pandas as pd

df = pd.read_csv("outputs/decision_log.csv")

df.head()

import json

with open("outputs/metrics.json") as f:
    metrics = json.load(f)

metrics

from IPython.display import Image

Image("outputs/figures/02_confusion_matrix.png")

!uvicorn src.app:app --host 127.0.0.1 --port 8000 &

import threading
import uvicorn

def run():
    uvicorn.run("src.app:app", host="127.0.0.1", port=8000)

thread = threading.Thread(target=run)
thread.start()

import requests

response = requests.get("http://127.0.0.1:8000/health")

print(response.json())

import requests

payload = {
    "room_id": "room_101",
    "device_id": "env_node_01",
    "timestamp": "2015-02-06 06:32:00",
    "Temperature": 21.93,
    "Humidity": 28.786,
    "Light": 469.53,
    "CO2": 834.85,
    "HumidityRatio": 0.001824
}

response = requests.post(
    "http://127.0.0.1:8000/predict",
    json=payload
)

print(response.json())

!python src/test_api.py